[phases.setup]
nixPkgs = ["nodejs_22"]

[phases.install]
cmds = ["npm ci --prefer-offline --no-audit --include=dev"]

[phases.build]
cmds = ["npm run build"]

[start]
cmd = "NODE_ENV=production node server/index.js"

[variables]
NODE_ENV = "production"
NIXPACKS_NO_CADDY = "1"
